import { FormEvent, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";

/**
 * Admin sign-up. The very first admin (root) signs up for free — has_any_admin()
 * tells us no admin exists yet. Every admin after that needs a single-use invite
 * code, generated by an existing admin from Settings → Invite an admin.
 */
export default function SignUpPage() {
  const [checking, setChecking] = useState(true);
  const [isRootSignup, setIsRootSignup] = useState(false);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [needsEmailConfirm, setNeedsEmailConfirm] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    supabase.rpc("has_any_admin").then(({ data, error }) => {
      // Fail closed: if the check itself errors, treat it as "an admin exists"
      // so we don't accidentally let someone skip the invite code.
      setIsRootSignup(error ? false : !data);
      setChecking(false);
    });
  }, []);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);

    if (password.length < 8) {
      setError("Password must be at least 8 characters.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords don't match.");
      return;
    }
    if (!isRootSignup && !inviteCode.trim()) {
      setError("Enter your invite code.");
      return;
    }

    setBusy(true);

    if (!isRootSignup) {
      // Redeem the code first — it's burned the moment this succeeds, even if
      // sign-up itself fails afterward (e.g. email already registered). That's
      // an intentional trade-off for keeping this simple; if that happens, just
      // generate a fresh code from Settings.
      const { data: redeemed, error: redeemError } = await supabase.rpc("redeem_invite_code", {
        p_code: inviteCode.trim(),
        p_email: email,
      });
      if (redeemError || !redeemed) {
        setBusy(false);
        setError("That invite code is invalid or has already been used.");
        return;
      }
    }

    const { data, error: signUpError } = await supabase.auth.signUp({ email, password });
    setBusy(false);

    if (signUpError) {
      setError(signUpError.message);
      return;
    }
    if (data.session) {
      // Auto-confirmed (email confirmations off) — straight into the dashboard.
      navigate("/admin");
    } else {
      // Email confirmation is on for this project — they'll confirm, then log in normally.
      setNeedsEmailConfirm(true);
    }
  }

  if (checking) return <div className="min-h-screen bg-bg" />;

  if (needsEmailConfirm) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4 text-center">
        <Card className="w-full max-w-sm p-8">
          <span className="mono-label text-cyan">Check your email</span>
          <h1 className="text-xl mt-3 mb-3">Confirm your address to finish setup.</h1>
          <p className="text-muted text-sm mb-6">
            We sent a confirmation link to {email}. Once confirmed, sign in as usual.
          </p>
          <Link to="/admin/login">
            <Button variant="ghost" className="w-full">
              Go to sign in
            </Button>
          </Link>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center px-4">
      <Card className="w-full max-w-sm p-8">
        <div className="flex items-center gap-2 mb-8">
          <div className="w-[30px] h-[30px] rounded-sm bg-cyan-soft border border-cyan/45 flex items-center justify-center text-cyan text-xs font-bold">
            MM
          </div>
          <span className="font-head font-bold text-lg">Minds Makers</span>
        </div>
        <span className="mono-label text-cyan">{isRootSignup ? "One-time setup" : "Admin sign up"}</span>
        <h1 className="text-2xl mt-2 mb-2">
          {isRootSignup ? "Create the root admin account" : "Create your account"}
        </h1>
        <p className="text-faint text-sm mb-6">
          {isRootSignup
            ? "No admin exists yet, so this one's free. After this, every new admin needs an invite code."
            : "You'll need an invite code from an existing admin."}
        </p>
        <form onSubmit={onSubmit} className="flex flex-col gap-4">
          <Input
            type="email"
            placeholder="you@mindsmakers.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            autoComplete="email"
          />
          <Input
            type="password"
            placeholder="Password (min 8 characters)"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            autoComplete="new-password"
          />
          <Input
            type="password"
            placeholder="Confirm password"
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            required
            autoComplete="new-password"
          />
          {!isRootSignup && (
            <Input
              type="text"
              placeholder="Invite code"
              value={inviteCode}
              onChange={(e) => setInviteCode(e.target.value)}
              required
            />
          )}
          {error && <p className="text-err text-sm">{error}</p>}
          <Button type="submit" disabled={busy}>
            {busy ? "Creating…" : "Create account"}
          </Button>
          <Link to="/admin/login" className="text-faint text-sm hover:text-muted text-center">
            Already have an account? Sign in
          </Link>
        </form>
      </Card>
    </div>
  );
}
